//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje.Models.Entit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOtelEntities2 : DbContext
    {
        public DbOtelEntities2()
            : base("name=DbOtelEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hakkimda> Hakkimda { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<mesajlar> mesajlar { get; set; }
        public virtual DbSet<YeniKayit> YeniKayit { get; set; }
        public virtual DbSet<TblRez> TblRez { get; set; }
    }
}
