//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje.Models.Entit
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRez
    {
        public int RezID { get; set; }
        public Nullable<int> Misafi { get; set; }
        public Nullable<System.DateTime> Giris { get; set; }
        public Nullable<System.DateTime> Cikis { get; set; }
        public string Kisi { get; set; }
        public string Oda { get; set; }
        public string RezAd { get; set; }
        public string Telefon { get; set; }
    }
}
